version: '3.8'

services:
  coding-challenge:
    build:
      context: .
      target: develop
    ports:
      - 5053:80
    container_name: coding-challenge
    volumes:
      - /code/node_modules
      - /code/build
      - ./:/code
    command: npm run dev
  coding-challenge-test:
    build:
      context: .
      target: develop
    ports:
      - 5053:80
    container_name: coding-challenge-tests
    volumes:
      - /code/node_modules
      - /code/build
      - ./:/code
    command: npm run test
